#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: Robot/pose
        pose2d: Robot/ground_pose
        child_frame_id: Robot/base_link
        parent_frame_id: world
    '2':
        pose: Obstacle/pose
        pose2d: Obstacle/ground_pose
        child_frame_id: Obstacle/base_link
        parent_frame_id: world
    '3':
        pose: Gesture/pose
        pose2d: Gesture/ground_pose
        child_frame_id: Gesture/base_link
        parent_frame_id: world
optitrack_config:
        multicast_address: 224.0.0.1
